(() => {
  "use strict";

  // DEMO AISLADA: no importa ni consulta rutas.js, rutas-config.js, Worker, D1 u OpenAI.
  const app = document.getElementById("demoApp");
  const bloqueo = document.getElementById("bloqueoDemo");
  if (bloqueo) bloqueo.hidden = true;
  if (app) app.hidden = false;

  const esc = (v) => String(v ?? "").replace(/[&<>\"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const mapsSearch = q => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;
  const mapsDir = (origin, destination, waypoints=[]) => {
    const p = new URLSearchParams({api:"1",origin,destination,travelmode:"driving"});
    if (waypoints.length) p.set("waypoints", waypoints.join("|"));
    return `https://www.google.com/maps/dir/?${p}`;
  };

  const BASES = {
    barcelona:{name:"Camping Barcelona",type:"Camping",address:"Avinguda del Maresme, 665, 08304 Mataró, Barcelona",why:"Base práctica para dejar la autocaravana y visitar Barcelona mediante el transporte propio del camping y la red pública.",web:"https://www.campingbarcelona.com/es/",maps:mapsSearch("Camping Barcelona Mataró")},
    montserrat:{name:"Càmping Montserrat",type:"Camping",address:"Sant Salvador de Guardiola, Barcelona",why:"Base tranquila frente al macizo de Montserrat, adecuada para combinar monasterio, miradores y senderismo.",web:"https://campingmontserrat.cat/",maps:mapsSearch("Càmping Montserrat Sant Salvador de Guardiola")},
    portaventura:{name:"Parking Caravaning PortAventura World",type:"Área oficial de autocaravanas",address:"Avinguda Alcalde Pere Molas, s/n, 43480 Vila-seca, Tarragona",why:"Permite dormir dentro del complejo y acceder a pie a PortAventura World. La estancia y las entradas forman parte del paquete oficial.",web:"https://www.portaventuraworld.com/hoteles/estacionamiento-autocaravanas",maps:mapsSearch("Parking Caravaning PortAventura World")},
    delta:{name:"Yelloh! Village Alfacs",type:"Camping",address:"Av. Mar, 1, 43530 Alcanar Platja, Tarragona",why:"Camping frente al Mediterráneo y bien situado para descubrir el Delta del Ebro, sus arrozales y su costa.",web:"https://www.alfacs.com/es",maps:mapsSearch("Yelloh Village Alfacs Alcanar")},
    valencia:{name:"Valencia Camper Park",type:"Área camper",address:"Bétera, València",why:"Base pensada para no mover la autocaravana durante dos días y entrar a València en transporte público.",web:"https://valenciacamperpark.com/",maps:mapsSearch("Valencia Camper Park Bétera")},
    alicante:{name:"Camper Park Alicante",type:"Área camper",address:"El Campello, Alicante",why:"Base próxima a la costa y conectada con Alicante, adecuada para una etapa urbana y de playa.",web:"https://camperparkalicante.com/",maps:mapsSearch("Camper Park Alicante El Campello")},
    cartagena:{name:"Área Autocaravanas Cartagena",type:"Área de servicio para autocaravanas",address:"Camino Molino Derribao, s/n, Los Dolores, Cartagena",why:"Área incluida en la información turística oficial de Cartagena y bien situada para combinar patrimonio urbano y Cabo de Palos.",web:"https://www.areaautocaravanas.com/",maps:mapsSearch("Área Autocaravanas Cartagena Los Dolores")},
    granada:{name:"Camping Las Lomas",type:"Camping",address:"Güéjar Sierra, Granada",why:"Base estratégica durante dos noches: Granada y Alhambra por un lado, y Sierra Nevada por otro, evitando mover de alojamiento cada día.",web:"https://www.campinglaslomas.com/",maps:mapsSearch("Camping Las Lomas Güéjar Sierra")},
    malaga:{name:"Área Málaga Beach",type:"Área de autocaravanas",address:"La Cala del Moral / Málaga Este",why:"Pernocta junto al litoral con servicios para autocaravanas y posibilidad de dejar el vehículo para visitar Málaga en transporte público.",web:"https://areamalagabeach.com/",maps:mapsSearch("Área Málaga Beach")},
    ardales:{name:"Camping Parque Ardales",type:"Camping",address:"Parque Ardales, Embalses del Guadalhorce, Málaga",why:"La base natural para realizar el Caminito del Rey desde el acceso norte y dormir junto a los embalses.",web:"https://www.parqueardales.com/",maps:mapsSearch("Camping Parque Ardales")},
    ronda:{name:"Camping El Sur",type:"Camping",address:"Carretera Ronda-Algeciras, km 1,5, 29400 Ronda",why:"Acceso cómodo sin atravesar el centro y a aproximadamente un kilómetro del casco histórico de Ronda.",web:"https://www.campingelsur.com/es/",maps:mapsSearch("Camping El Sur Ronda")},
    sevilla:{name:"Camping Villsom",type:"Camping",address:"Dos Hermanas, Sevilla",why:"Base exterior para dejar la autocaravana y entrar a Sevilla en transporte público.",web:"https://www.campingvillsom.com/",maps:mapsSearch("Camping Villsom Dos Hermanas Sevilla")}
  };

  const rec = (name, why, category, q, web="") => ({name,why,category,maps:mapsSearch(q||name),web});
  const food = (name, why, specialty, q, web="") => ({name,why,specialty,maps:mapsSearch(q||name),web});

  const days = [
    {day:1,title:"Barcelona · modernismo, casco histórico y Mediterráneo",place:"Barcelona",lat:41.3874,lon:2.1686,stay:false,drive:"Llegada y primera jornada urbana",plan:"Empieza la ruta sin prisas: deja la autocaravana en Mataró y entra a Barcelona. La prioridad es combinar una gran visita monumental con paseo por el centro histórico y ambiente mediterráneo, sin convertir el primer día en una carrera.",visits:[rec("Basílica de la Sagrada Família","La obra más reconocible de Gaudí y una apertura espectacular para la ruta.","Arquitectura · patrimonio","Sagrada Família Barcelona","https://sagradafamilia.org/"),rec("Barrio Gótico","Calles históricas, plazas y restos de la Barcelona medieval y romana.","Centro histórico","Barri Gòtic Barcelona","https://www.barcelonaturisme.com/")],food:[food("Mercat de la Boqueria","Una forma fácil de introducirse en producto local y cocina catalana en pleno centro.","Producto catalán, tapas y mercado","Mercat de la Boqueria Barcelona","https://www.boqueria.barcelona/")],base:BASES.barcelona,warning:"Reserva con antelación la Sagrada Família y comprueba los horarios del transporte del camping hacia Barcelona.",photo:"https://upload.wikimedia.org/wikipedia/commons/c/c8/Sagrada_Fam%C3%ADlia%2C_Pla%C3%A7a_de_Gaud%C3%AD%2C_Barcelona_-_panoramio_%281%29.jpg",photoSource:"https://commons.wikimedia.org/wiki/File:Sagrada_Fam%C3%ADlia,_Pla%C3%A7a_de_Gaud%C3%AD,_Barcelona_-_panoramio_(1).jpg",photoCredit:"Wikimedia Commons · ficha de autor y licencia"},
    {day:2,title:"Barcelona → Montserrat · montaña y monasterio",place:"Montserrat",lat:41.5932,lon:1.8372,stay:false,drive:"🚐 aprox. 55 km · alrededor de 1 h",plan:"Cambio completo de escenario. Tras el traslado corto, dedica el día al monasterio, los miradores y un sendero asumible para una jornada familiar. El Camí dels Degotalls es una buena alternativa cuando se busca caminar sin afrontar una ruta larga o técnica.",visits:[rec("Monasterio de Montserrat","Santuario, patrimonio y uno de los paisajes de montaña más singulares de Cataluña.","Patrimonio · naturaleza","Monestir de Montserrat","https://www.montserratvisita.com/"),rec("Camí dels Degotalls","Sendero oficial corto y accesible para sumar naturaleza sin ocupar toda la jornada.","Senderismo","Camí dels Degotalls Montserrat","https://www.montserratvisita.com/en/nature/montserrat-itineraries/degotalls-path")],food:[food("Montserrat · gastronomía local","Completa la visita con cocina catalana de montaña y productos de la zona.","Cocina catalana","restaurants Montserrat monastery")],base:BASES.montserrat,warning:"La apertura del camping es estacional. Consulta disponibilidad y condiciones actuales antes del viaje."},
    {day:3,title:"Montserrat → PortAventura World · día familiar",place:"PortAventura World",lat:41.0879,lon:1.1575,stay:false,drive:"🚐 aprox. 110 km · alrededor de 1 h 20 min",plan:"Jornada diseñada para familias: llegar, instalarse en el Parking Caravaning y dedicar el resto del día al parque. PortAventura Park es la prioridad; Ferrari Land queda como opción si la entrada y el horario real lo permiten.",visits:[rec("PortAventura Park","Más de cuarenta atracciones y áreas tematizadas para convertir el tercer día en un cambio total de ritmo.","Parque temático · familia","PortAventura Park","https://www.portaventuraworld.com/portaventura"),rec("Ferrari Land","Complemento opcional si encaja con la modalidad de entrada y los horarios del día.","Parque temático","Ferrari Land","https://www.portaventuraworld.com/ferrari-land")],food:[food("Gold River Saloon","Opción práctica dentro del complejo para evitar desplazamientos adicionales.","Comida informal","Gold River Saloon PortAventura","https://www.portaventuraworld.com/")],base:BASES.portaventura,warning:"El Parking Caravaning permite un máximo de dos noches y forma parte de un paquete con entradas. Comprueba calendario, modalidad de entrada, check-in y condiciones vigentes."},
    {day:4,title:"PortAventura → Delta del Ebro · arrozales, aves y mar",place:"Delta del Ebro",lat:40.7050,lon:0.7180,stay:false,drive:"🚐 aprox. 70 km · alrededor de 1 h",plan:"Después del parque, toca una jornada de naturaleza. Recorre el Delta con calma, observa aves, atraviesa paisajes de arrozales y reserva tiempo para la costa. Es un día ideal para bicicleta o paseo corto según el calor y el viento.",visits:[rec("Parc Natural del Delta de l'Ebre","Humedales, lagunas, arrozales y una de las zonas ornitológicas más importantes del Mediterráneo occidental.","Naturaleza · fauna","Parc Natural del Delta de l'Ebre","https://parcsnaturals.gencat.cat/ca/xarxa-de-parcs/delta-ebre/"),rec("Platja del Trabucador","Gran lengua de arena para terminar la jornada frente al mar y entender la geografía del Delta.","Costa · paisaje","Platja del Trabucador")],food:[food("La Salina · Alfacs","Opción vinculada al propio camping para probar pescado, marisco y cocina del Delta sin mover la autocaravana.","Arroz, pescado y marisco","La Salina Alfacs","https://www.alfacs.com/es")],base:BASES.delta,warning:"El camping tiene temporada de apertura. Consulta fechas actuales y, si visitas zonas naturales, respeta cierres, fauna y restricciones de acceso."},
    {day:5,title:"Delta del Ebro → València · centro histórico y Turia",place:"València",lat:39.4699,lon:-0.3763,stay:false,drive:"🚐 aprox. 195 km · alrededor de 2 h",plan:"Instálate en la base antes de entrar a la ciudad. Dedica la tarde al Mercado Central, la Lonja y el entorno de la plaza de la Virgen, terminando con un paseo por el Jardín del Turia. La idea es reservar la arquitectura contemporánea y el Oceanogràfic para mañana.",visits:[rec("Mercado Central de València","Arquitectura modernista y producto local en uno de los mercados más emblemáticos de Europa.","Mercado · gastronomía","Mercat Central València","https://www.mercadocentralvalencia.es/"),rec("La Lonja de la Seda","Patrimonio mundial y pieza clave para entender la riqueza mercantil histórica de València.","Patrimonio","Lonja de la Seda Valencia","https://www.visitvalencia.com/")],food:[food("Casa Carmela","Una referencia clásica para acercarse al arroz valenciano junto al Mediterráneo.","Paella valenciana y arroces","Casa Carmela Valencia","https://www.casa-carmela.com/")],base:BASES.valencia,warning:"Deja la autocaravana en la base y utiliza transporte público para evitar accesos urbanos innecesarios."},
    {day:6,title:"València · Ciudad de las Artes, Oceanogràfic y playa",place:"València",lat:39.4549,lon:-0.3504,stay:true,drive:"Sin traslado principal · misma base",plan:"Día completo sin mover la autocaravana. La Ciudad de las Artes y las Ciencias y el Oceanogràfic ocupan el núcleo de la jornada; el Jardín del Turia y la playa quedan como complemento según energía, edad de los viajeros y horario real.",visits:[rec("Ciudad de las Artes y las Ciencias","Uno de los conjuntos contemporáneos más reconocibles de España y un excelente día visual para la demo.","Arquitectura · ciencia","Ciutat de les Arts i les Ciències","https://cac.es/"),rec("Oceanogràfic","Gran acuario y visita especialmente atractiva para familias con niños.","Familia · acuario","Oceanogràfic València","https://www.oceanografic.org/")],food:[food("València marítima","Aprovecha la jornada para probar otro arroz o cocina de producto cerca del frente marítimo.","Arroces y producto mediterráneo","restaurants Marina Valencia")],base:BASES.valencia,warning:"Entradas y horarios del Oceanogràfic y de los recintos pueden variar. Consulta información actual.",sameBase:true},
    {day:7,title:"València → Alicante · castillo, casco antiguo y playa",place:"Alicante",lat:38.3452,lon:-0.4810,stay:false,drive:"🚐 aprox. 180 km · alrededor de 2 h",plan:"Traslado directo a Alicante y tarde para combinar el Castillo de Santa Bárbara, el barrio de Santa Cruz, la Explanada y el Mediterráneo. El castillo domina la bahía y ofrece una lectura perfecta de la ciudad.",visits:[rec("Castillo de Santa Bárbara","Fortaleza sobre el monte Benacantil con vistas abiertas a Alicante y su bahía.","Castillo · mirador","Castillo de Santa Bárbara Alicante","https://www.alicante.es/es/equipamientos/castillo-santa-barbara"),rec("Explanada de España","Paseo marítimo emblemático para terminar la visita urbana junto al puerto.","Paseo urbano","Explanada de España Alicante")],food:[food("Nou Manolín","Clásico alicantino para acercarse a tapas, pescado y cocina de producto.","Tapas, marisco y arroces","Nou Manolín Alicante","https://grupogastronou.com/")],base:BASES.alicante,warning:"No planifiques subir con la autocaravana al castillo. Consulta los accesos vigentes y utiliza las opciones peatonales o de transporte habilitadas.",photo:"https://upload.wikimedia.org/wikipedia/commons/5/5a/Alicante_Castillo_de_Santa_B%C3%A1rbara_01.jpg",photoSource:"https://commons.wikimedia.org/wiki/File:Alicante_Castillo_de_Santa_B%C3%A1rbara_01.jpg",photoCredit:"Wikimedia Commons · ficha de autor y licencia"},
    {day:8,title:"Alicante → Cartagena y Cabo de Palos · Roma y Mediterráneo",place:"Cartagena",lat:37.6257,lon:-0.9966,stay:false,drive:"🚐 aprox. 110–120 km · alrededor de 1 h 30 min",plan:"Dos caras de Murcia en un mismo día: patrimonio romano por la mañana y costa por la tarde. El Teatro Romano y el casco histórico justifican Cartagena; Cabo de Palos añade faro, mar y ambiente pesquero. El snorkel es opcional y solo con condiciones adecuadas.",visits:[rec("Teatro Romano de Cartagena","Uno de los grandes conjuntos arqueológicos urbanos de la península, integrado en el centro de Cartagena.","Arqueología · patrimonio","Museo Teatro Romano Cartagena","https://puertodeculturas.cartagena.es/"),rec("Cabo de Palos","Faro, costa rocosa y ambiente marinero a unos treinta kilómetros de Cartagena.","Costa · faro","Faro de Cabo de Palos")],food:[food("Cartagena y Cabo de Palos","Buen día para pescado, caldero y cocina del Mar Menor/Costa Cálida.","Pescado, caldero y cocina murciana","restaurants Cabo de Palos")],base:BASES.cartagena,warning:"Si haces snorkel, comprueba mar, viento, zona autorizada y condiciones personales. No se presenta como una actividad obligatoria."},
    {day:9,title:"Cartagena → Granada · Alhambra, Albaicín y tapas",place:"Granada",lat:37.1761,lon:-3.5881,stay:false,drive:"🚐 aprox. 280 km · alrededor de 3 h",plan:"Es la etapa de conducción más larga. Instálate primero en Las Lomas y evita sobrecargar la tarde. Reserva la Alhambra con antelación y completa el día con un paseo por Albaicín o un mirador y algo de tapeo, ajustándolo a la hora real de llegada.",visits:[rec("Alhambra y Generalife","El gran conjunto monumental nazarí y una de las visitas imprescindibles de toda la ruta.","Patrimonio mundial","Alhambra Granada","https://www.alhambra-patronato.es/"),rec("Albaicín y miradores","Barrio histórico de calles estrechas y vistas hacia la Alhambra y Sierra Nevada.","Barrio histórico","Mirador de San Nicolás Granada","https://turismo.granada.org/")],food:[food("Bodegas Castañeda","Opción tradicional para una introducción al tapeo granadino en el centro.","Tapas y cocina granadina","Bodegas Castañeda Granada")],base:BASES.granada,warning:"⚠️ Importante para autocaravanas: el propio Camping Las Lomas desaconseja llegar por Beas de Granada. Usa el acceso recomendado por Granada → A-395 → Pinos Genil → Güéjar Sierra."},
    {day:10,title:"Sierra Nevada · naturaleza y montaña",place:"Sierra Nevada",lat:37.0953,lon:-3.3986,stay:true,drive:"Sin cambio de base · excursión local",plan:"Segundo día desde Las Lomas, ahora dedicado a la montaña. Elige un paseo o sendero oficial acorde a la meteorología, la época del año y la capacidad del grupo. La ruta demuestra cómo una misma base puede servir un día para patrimonio y otro para naturaleza.",visits:[rec("Sierra Nevada","Alta montaña mediterránea con senderos, miradores y paisajes que contrastan por completo con Granada ciudad.","Montaña · naturaleza","Sierra Nevada Granada","https://sierranevada.es/"),rec("Güéjar Sierra","Pueblo de montaña y buen complemento para una jornada menos exigente.","Pueblo · montaña","Güéjar Sierra Granada")],food:[food("Güéjar Sierra · cocina de montaña","Una jornada adecuada para platos serranos y cocina granadina más contundente.","Cocina serrana","restaurants Güéjar Sierra")],base:BASES.granada,warning:"En montaña no congeles una ruta exacta: comprueba meteorología, estado de senderos, altitud y servicios abiertos el mismo día.",sameBase:true},
    {day:11,title:"Granada → Málaga · Alcazaba, centro y mar",place:"Málaga",lat:36.7213,lon:-4.4214,stay:false,drive:"🚐 aprox. 125 km · alrededor de 1 h 30 min",plan:"Baja de Sierra Nevada al Mediterráneo, instala la autocaravana en Málaga Beach y entra a la ciudad sin moverla. Alcazaba y Gibralfaro, centro histórico y Muelle Uno ofrecen una jornada completa con distancias urbanas razonables.",visits:[rec("Alcazaba de Málaga","Fortaleza palaciega andalusí sobre el centro histórico y uno de los grandes símbolos de la ciudad.","Fortaleza · patrimonio","Alcazaba Málaga","https://visita.malaga.eu/"),rec("Muelle Uno y Palmeral de las Sorpresas","Paseo portuario para terminar el día junto al Mediterráneo.","Puerto · paseo","Muelle Uno Málaga","https://www.muelleuno.com/")],food:[food("El Tintero","Un clásico junto al mar para pescados y espetos, con una experiencia muy malagueña.","Pescado, espetos y marisco","El Tintero Málaga","https://www.el-tintero.com/")],base:BASES.malaga,warning:"⚠️ Acceso en autocaravana: evita la salida 3 de La Araña/MA-24 indicada como problemática por gálibo. Sigue las instrucciones de acceso actuales del área."},
    {day:12,title:"Málaga → Ardales · Caminito del Rey y El Chorro",place:"Caminito del Rey",lat:36.9167,lon:-4.7725,stay:false,drive:"🚐 aprox. 50–60 km · alrededor de 50 min",plan:"Una de las jornadas estrella. Instálate primero en Parque Ardales y afronta el Caminito como recorrido lineal desde el acceso norte hacia El Chorro. Reserva tiempo para el acceso a pie, las pasarelas, el desfiladero y la lanzadera de regreso.",visits:[rec("Caminito del Rey","Recorrido lineal por el Desfiladero de los Gaitanes, con pasarelas suspendidas y un paisaje geológico excepcional.","Senderismo · paisaje","Caminito del Rey Ardales","https://www.caminitodelrey.info/"),rec("El Chorro","Final natural del recorrido, paisaje ferroviario y enclave histórico de escalada.","Paisaje · escalada","El Chorro Málaga")],food:[food("Restaurante El Kiosko","Punto clásico en el entorno del acceso norte, práctico para completar el día junto a los embalses.","Cocina malagueña","Restaurante El Kiosko Ardales")],base:BASES.ardales,warning:"Reserva previa obligatoria. Comprueba hora de acceso, tiempo de aproximación, lanzadera y normas actuales. Menores y condiciones meteorológicas están sujetos a las reglas oficiales del Caminito.",curiosity:"🎬 El Chorro, un paisaje de cine. El ferrocarril, los túneles y el Desfiladero de los Gaitanes aparecen en Von Ryan's Express (1965), protagonizada por Frank Sinatra. Como curiosidad adicional, el entorno también llegó a representar Afganistán en The Horsemen (1971). El protagonismo del día sigue siendo el paisaje, el Caminito y la historia ferroviaria."},
    {day:13,title:"Ardales → Ronda · Puente Nuevo y ciudad histórica",place:"Ronda",lat:36.7420,lon:-5.1672,stay:false,drive:"🚐 aprox. 50 km · alrededor de 1 h",plan:"Etapa corta después del Caminito. Instálate en Camping El Sur y entra a Ronda a pie o con el medio más conveniente. El Puente Nuevo, los miradores y la ciudad histórica llenan el día sin necesidad de más kilómetros.",visits:[rec("Puente Nuevo","La imagen más reconocible de Ronda, suspendida sobre el Tajo y núcleo visual de la jornada.","Arquitectura · paisaje","Puente Nuevo Ronda","https://www.turismoderonda.es/"),rec("Casco histórico de Ronda","Palacios, calles blancas y miradores sobre la Serranía.","Centro histórico","Ronda casco histórico","https://www.turismoderonda.es/")],food:[food("Pedro Romero","Restaurante tradicional vinculado a la cocina rondeña y andaluza.","Cocina rondeña","Restaurante Pedro Romero Ronda")],base:BASES.ronda,warning:"El camping permite evitar atravesar el centro con la autocaravana; aprovecha esa ventaja y visita Ronda con el vehículo estacionado."},
    {day:14,title:"Ronda → Sevilla · Triana, Guadalquivir y noche sevillana",place:"Sevilla",lat:37.3891,lon:-5.9845,stay:false,drive:"🚐 aprox. 130–150 km · alrededor de 1 h 45 min",plan:"Llega a Villsom, deja la autocaravana y dedica la primera tarde sevillana a Triana, el Guadalquivir y el centro. Así el día 15 queda reservado para los grandes monumentos sin prisas.",visits:[rec("Triana","Barrio con identidad propia, cerámica, mercado y una de las mejores entradas a la Sevilla del río.","Barrio · cultura","Triana Sevilla","https://visitasevilla.es/"),rec("Paseo del Guadalquivir","Torre del Oro, puentes y ambiente de tarde junto al río.","Paseo urbano","Torre del Oro Sevilla","https://visitasevilla.es/")],food:[food("Casa Morales","Taberna histórica para introducirse en tapas sevillanas en pleno centro.","Tapas sevillanas","Casa Morales Sevilla")],base:BASES.sevilla,warning:"Comprueba los horarios actuales del transporte entre Dos Hermanas/Camping Villsom y Sevilla antes de salir."},
    {day:15,title:"Sevilla · Alcázar, Catedral y Plaza de España",place:"Sevilla",lat:37.3772,lon:-5.9869,stay:true,drive:"Día final · sin nueva pernocta",plan:"Gran cierre de la ruta. Alcázar, Catedral y Giralda forman el bloque monumental; Santa Cruz, Plaza de España y María Luisa aportan paseo y paisaje urbano. Termina junto al Guadalquivir o con una última cena de tapas. La ruta acaba aquí: 15 días y 14 noches.",visits:[rec("Real Alcázar de Sevilla","Conjunto palaciego imprescindible y uno de los grandes finales posibles para una ruta por España.","Patrimonio mundial","Real Alcázar Sevilla","https://www.alcazarsevilla.org/"),rec("Catedral y Giralda","Uno de los conjuntos monumentales más importantes de Sevilla.","Patrimonio · arquitectura","Catedral de Sevilla","https://www.catedraldesevilla.es/"),rec("Plaza de España y Parque de María Luisa","Espacio monumental y jardines para cerrar la ruta al aire libre.","Parque · arquitectura","Plaza de España Sevilla","https://visitasevilla.es/")],food:[food("Sevilla · despedida de tapas","Última comida o cena para cerrar la ruta con cocina andaluza sin añadir otra etapa de conducción.","Tapas y cocina sevillana","tapas Sevilla centro")],warning:"No se añade una noche 15 ficticia: la demostración termina en Sevilla después de completar el día."}
  ];

  const routePoints = [
    [41.3874,2.1686,"Barcelona"],[41.5932,1.8372,"Montserrat"],[41.0879,1.1575,"PortAventura"],[40.7050,0.7180,"Delta del Ebro"],[39.4699,-0.3763,"València"],[38.3452,-0.4810,"Alicante"],[37.6257,-0.9966,"Cartagena"],[37.1761,-3.5881,"Granada"],[36.7213,-4.4214,"Málaga"],[36.9167,-4.7725,"Ardales"],[36.7420,-5.1672,"Ronda"],[37.3891,-5.9845,"Sevilla"]
  ];

  const totalKm = "aprox. 1.500 km";
  document.getElementById("metricasRuta").innerHTML = [
    ["15 días","Duración"],["14 noches","Pernoctas"],[totalKm,"Recorrido principal"],["12 bases","Campings / áreas"]
  ].map(([a,b])=>`<div class="metrica"><strong>${esc(a)}</strong><span>${esc(b)}</span></div>`).join("");

  const wholeRoute = mapsDir("Barcelona, Spain","Sevilla, Spain",["Montserrat, Spain","PortAventura World","Delta del Ebro","Valencia, Spain","Alicante, Spain","Cartagena, Spain","Granada, Spain","Malaga, Spain","Ardales, Spain","Ronda, Spain"]);
  document.getElementById("navegacionRuta").innerHTML = `<a href="${wholeRoute}" target="_blank" rel="noopener">🧭 Navegar esta ruta con Google Maps</a>`;

  const links = (x) => {
    const a=[];
    if(x.maps)a.push(`<a href="${esc(x.maps)}" target="_blank" rel="noopener">📍 Abrir en Google Maps</a>`);
    if(x.web)a.push(`<a href="${esc(x.web)}" target="_blank" rel="noopener">🌐 Web oficial</a>`);
    return a.length?`<div class="guia-enlaces">${a.join("")}</div>`:"";
  };
  const recommendation = (x,kind,principal=false) => `<div class="guia-recomendacion ${principal?"principal":""}"><h4>${principal?"⭐ ":""}${esc(x.name)}</h4>${x.why?`<p><strong>${kind==="food"?"Por qué lo recomendamos":"Por qué merece la pena"}:</strong> ${esc(x.why)}</p>`:""}${x.category?`<p><strong>Qué vas a visitar:</strong> ${esc(x.category)}</p>`:""}${x.specialty?`<p><strong>🍴 Qué probar:</strong> ${esc(x.specialty)}</p>`:""}${x.type?`<p><strong>Tipo:</strong> ${esc(x.type)}</p>`:""}${x.address?`<p><strong>📍 Dirección:</strong> ${esc(x.address)}</p>`:""}${links(x)}</div>`;

  const routeByDay = (d, idx) => {
    const next = days[idx+1];
    if(d.stay || !next) return mapsSearch(d.place);
    return mapsDir(d.place,next.place);
  };

  document.getElementById("etapasRuta").innerHTML = days.map((d,i)=>{
    const cls=d.stay?"dia-estancia":"dia-conduccion";
    const badge=d.stay?'<span class="badge-estancia">🏡 Día de estancia y visitas</span>':"";
    const photo=d.photo?`<figure class="guia-foto"><img loading="lazy" src="${esc(d.photo)}" alt="${esc(d.title)}"><figcaption>${esc(d.photoCredit||"Wikimedia Commons")} · <a href="${esc(d.photoSource||d.photo)}" target="_blank" rel="noopener">fuente/licencia</a></figcaption></figure>`:"";
    const overnight = d.base ? (d.sameBase
      ? `<section class="guia-seccion-editorial"><h3>🌙 Pernocta</h3><p>Para evitar mover la autocaravana innecesariamente, mantenemos como base <strong>${esc(d.base.name)}</strong> durante la estancia.</p>${links(d.base)}</section>`
      : `<section class="guia-seccion-editorial"><h3>🚐 Dónde dormir</h3><div class="guia-recomendaciones">${recommendation(d.base,"base",true)}</div></section>`)
      : "";
    return `<section class="guia-dia-editorial ${cls}" id="dia-${d.day}">
      <div class="guia-dia-titulo"><span>DÍA ${d.day}</span>${badge}<h2>${esc(d.title)}</h2><p>${esc(d.drive)}</p></div>
      ${photo}
      <div class="guia-narrativa"><strong>Plan del día.</strong> ${esc(d.plan)}</div>
      <section class="guia-seccion-editorial"><h3>🏛️ Visitas recomendadas</h3><div class="guia-recomendaciones">${d.visits.map((x,n)=>recommendation(x,"visit",n===0)).join("")}</div></section>
      <section class="guia-seccion-editorial"><h3>🍴 Dónde comer</h3><div class="guia-recomendaciones">${d.food.map((x,n)=>recommendation(x,"food",n===0)).join("")}</div></section>
      ${d.curiosity?`<section class="guia-seccion-editorial"><h3>🎬 Curiosidad del lugar</h3><div class="curiosidad">${esc(d.curiosity)}</div></section>`:""}
      ${overnight}
      <section class="guia-seccion-editorial"><h3>⚠️ Conviene comprobar antes de ir</h3><div class="aviso">${esc(d.warning)}</div><div class="ruta-dia"><a href="${esc(routeByDay(d,i))}" target="_blank" rel="noopener">🧭 Abrir etapa del día en Google Maps</a></div></section>
      <section class="guia-seccion-editorial"><h3>📌 Recomendación final</h3><p>${d.stay?"Aprovecha que hoy no hay un gran traslado: deja margen para descansar y adapta las visitas al ritmo real del grupo.":"No persigas el reloj. Las distancias son aproximadas y la prioridad es llegar con margen, instalar la autocaravana y disfrutar del destino."}</p></section>
    </section>`;
  }).join("");

  if (window.L && document.getElementById("mapaRuta")) {
    const map=L.map("mapaRuta",{scrollWheelZoom:false}).setView([39.3,-1.2],6);
    L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:18,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);
    const latlngs=routePoints.map(x=>[x[0],x[1]]);
    L.polyline(latlngs,{weight:5,opacity:.78}).addTo(map);
    routePoints.forEach((p,i)=>{
      const icon=L.divIcon({className:"leaflet-div-icon",html:`<div class="marker-num">${i+1}</div>`,iconSize:[32,32],iconAnchor:[16,16]});
      L.marker([p[0],p[1]],{icon}).addTo(map).bindPopup(`<strong>${i+1}. ${esc(p[2])}</strong>`);
    });
    map.fitBounds(latlngs,{padding:[25,25]});
    setTimeout(()=>map.invalidateSize(),50);
  }
})();
