[
  {
    "id": "taller-at-001",
    "nombre": "A&O Camping",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Vorarlberg",
    "provincia": "Vorarlberg",
    "localidad": "Dornbirn",
    "lat": null,
    "lon": null,
    "telefono": "+43 5572 374426",
    "web": "https://aocamping.at/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Wallenmahd%2023%2C%206850%20Dornbirn%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-002",
    "nombre": "A.B.C. Reisemobile",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Oberösterreich",
    "provincia": "Oberösterreich",
    "localidad": "Kirchham",
    "lat": null,
    "lon": null,
    "telefono": "+43 7619 2002",
    "web": "https://www.beiskammer.at/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Kirchham%20Nr.%2018%2C%204656%20Kirchham%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-003",
    "nombre": "Auto & Technik Tresdorf",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Niederösterreich",
    "provincia": "Niederösterreich",
    "localidad": "Tresdorf",
    "lat": null,
    "lon": null,
    "telefono": "+43 2262 72516-0",
    "web": "https://www.autoundtechnik.at",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Lagerhausplatz%201a%2C%202111%20Tresdorf%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-004",
    "nombre": "Camper Neugebauer",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Kärnten",
    "provincia": "Kärnten",
    "localidad": "Magdalensberg",
    "lat": null,
    "lon": null,
    "telefono": "+43 677 61704907",
    "web": "https://www.camper-neugebauer.at/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Geiersdorf%209%2C%209064%20Magdalensberg%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-005",
    "nombre": "Camping Center Heiss",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Tirol",
    "provincia": "Tirol",
    "localidad": "Inzing",
    "lat": null,
    "lon": null,
    "telefono": "+43 5238 54055",
    "web": "https://www.campingheiss.at/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Schie%C3%9Fstand%203a%2C%206401%20Inzing%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-006",
    "nombre": "Camping.holiday CRC GmbH",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Niederösterreich",
    "provincia": "Niederösterreich",
    "localidad": "Bruck an der Leitha",
    "lat": null,
    "lon": null,
    "telefono": "+43 2162 62622",
    "web": "https://www.camping.holiday/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Alte%20Wiener%20Stra%C3%9Fe%2048-50%2C%202460%20Bruck%20an%20der%20Leitha%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-007",
    "nombre": "Campingtraum.at",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Oberösterreich",
    "provincia": "Oberösterreich",
    "localidad": "Weidenau",
    "lat": null,
    "lon": null,
    "telefono": "+43 7248 63701",
    "web": "http://www.campingtraum.at/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Gewerbepark%20Stritzing%2023%2C%204710%20Weidenau%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-008",
    "nombre": "Campingworld Neugebauer",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Niederösterreich",
    "provincia": "Niederösterreich",
    "localidad": "Neunkirchen",
    "lat": null,
    "lon": null,
    "telefono": "+43 2635 202220",
    "web": "https://camping-world.at/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Wienerstra%C3%9Fe%2096%2C%202620%20Neunkirchen%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-009",
    "nombre": "CARAmobil GesmbH",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Niederösterreich",
    "provincia": "Niederösterreich",
    "localidad": "Leopoldsdorf",
    "lat": null,
    "lon": null,
    "telefono": "+43 2235 43800",
    "web": "https://www.caramobil.at/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Arbeitergasse%2027A%2C%202333%20Leopoldsdorf%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-010",
    "nombre": "Caravan Prattes",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Steiermark",
    "provincia": "Steiermark",
    "localidad": "Bad Schwanberg",
    "lat": null,
    "lon": null,
    "telefono": "+43 676 7373212",
    "web": "https://www.caravan-prattes.at/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Wieserstra%C3%9Fe%2079%2C%208541%20Bad%20Schwanberg%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-011",
    "nombre": "CWN Sales & Service",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Oberösterreich",
    "provincia": "Oberösterreich",
    "localidad": "Vöcklabruck",
    "lat": null,
    "lon": null,
    "telefono": "+43 2635 202220",
    "web": "https://camping-world.at/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Telefunkenstra%C3%9Fe%2017%2C%204840%20V%C3%B6cklabruck%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-012",
    "nombre": "Exmanco Steyr",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Oberösterreich",
    "provincia": "Oberösterreich",
    "localidad": "Steyr-Gleink",
    "lat": null,
    "lon": null,
    "telefono": "+43 7252 47087",
    "web": "https://www.exmanco-steyr.at/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Im%20Stadtgut%20Zone%20D%206%2C%204407%20Steyr-Gleink%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-013",
    "nombre": "Falle Campingwelt",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Kärnten",
    "provincia": "Kärnten",
    "localidad": "Villach",
    "lat": null,
    "lon": null,
    "telefono": "+43 4242 32540",
    "web": "https://www.falle.at",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Maria-Gailer-Stra%C3%9Fe%2059%2C%209500%20Villach%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-014",
    "nombre": "Falle Campingwelt Outdoor & Freizeit",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Niederösterreich",
    "provincia": "Niederösterreich",
    "localidad": "Föhrenhain",
    "lat": null,
    "lon": null,
    "telefono": "+43 2246 27027",
    "web": "https://campingwelt.at/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Br%C3%BCnner%20Stra%C3%9Fe%20176-178%2C%202201%20F%C3%B6hrenhain%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-015",
    "nombre": "Ferdinand Berger GmbH & Co KG",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Oberösterreich",
    "provincia": "Oberösterreich",
    "localidad": "Redlham",
    "lat": null,
    "lon": null,
    "telefono": "+43 660 4018689",
    "web": "https://www.autowelt-berger.info/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Gewerbepark%20West%206%2C%204846%20Redlham%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-016",
    "nombre": "Funmobil",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Steiermark",
    "provincia": "Steiermark",
    "localidad": "Dobl-Zwaring",
    "lat": null,
    "lon": null,
    "telefono": "+43 3136 20070",
    "web": "https://www.funmobil.at/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Liebochstra%C3%9Fe%2011%2C%208143%20Dobl-Zwaring%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-017",
    "nombre": "Gebetsroither Weißenbach/Liezen",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Steiermark",
    "provincia": "Steiermark",
    "localidad": "Weißenbach bei Liezen",
    "lat": null,
    "lon": null,
    "telefono": "+43 3612 26300201",
    "web": "https://www.gebetsroither-camper.com",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Gebetsroitherweg%201%2C%208940%20Wei%C3%9Fenbach%20bei%20Liezen%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-018",
    "nombre": "KfZ Zweirad Friedrich Huber",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Niederösterreich",
    "provincia": "Niederösterreich",
    "localidad": "Klosterneuburg",
    "lat": null,
    "lon": null,
    "telefono": "+43 2243 26909",
    "web": "https://www.friedrich-huber.at/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Inkustra%C3%9Fe%201-7%2C%203400%20Klosterneuburg%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-019",
    "nombre": "Kledo Reisemobile",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Steiermark",
    "provincia": "Steiermark",
    "localidad": "Graz",
    "lat": null,
    "lon": null,
    "telefono": "+43 316 272795",
    "web": "https://kledo.at/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Gradnerstra%C3%9Fe%2066%2C%208055%20Graz%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-020",
    "nombre": "Pfaff Camping",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Niederösterreich",
    "provincia": "Niederösterreich",
    "localidad": "Ober-Grafendorf",
    "lat": null,
    "lon": null,
    "telefono": "+43 2747 2234",
    "web": "https://www.pfaff-camping.at/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Fridau%2031%2C%203200%20Ober-Grafendorf%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-021",
    "nombre": "Reisemobil & Wohnwagencenter Robert Harrer",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Steiermark",
    "provincia": "Steiermark",
    "localidad": "Passail",
    "lat": null,
    "lon": null,
    "telefono": "+43 3179 27395",
    "web": "https://www.robert-harrer.at/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Auen%2061%2C%208162%20Passail%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-022",
    "nombre": "Reisemobile Wenger",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Salzburg",
    "provincia": "Salzburg",
    "localidad": "Kuchl",
    "lat": null,
    "lon": null,
    "telefono": "+43 6244 4310",
    "web": "https://www.reisemobile-wenger.at/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Moos%2083%2C%205431%20Kuchl%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-023",
    "nombre": "RMC - Skohautil",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Niederösterreich",
    "provincia": "Niederösterreich",
    "localidad": "Sankt Pantaleon-Erla",
    "lat": null,
    "lon": null,
    "telefono": "+43 7435 74310",
    "web": "https://www.reisemobilcenter.at/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Erla%20100%2C%204303%20Sankt%20Pantaleon-Erla%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-024",
    "nombre": "STAR-Caravan Wohnwagen & Wohnmobilhandel",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Niederösterreich",
    "provincia": "Niederösterreich",
    "localidad": "Gerasdorf bei Wien",
    "lat": null,
    "lon": null,
    "telefono": "+43 2246 34111",
    "web": "https://star-caravan.at/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Am%20Weichselgarten%204%2C%202201%20Gerasdorf%20bei%20Wien%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-025",
    "nombre": "Sulzbacher",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Oberösterreich",
    "provincia": "Oberösterreich",
    "localidad": "Eferding",
    "lat": null,
    "lon": null,
    "telefono": "+43 7272 2542",
    "web": "https://www.sulzbacher.at/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Goldenberg%201%2C%204070%20Eferding%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-026",
    "nombre": "Wagner Gas",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Tirol",
    "provincia": "Tirol",
    "localidad": "Kufstein",
    "lat": null,
    "lon": null,
    "telefono": "+43 664 2030070",
    "web": "https://www.wagner-gas.at",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Untere%20Sparchen%2020%2C%206330%20Kufstein%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-027",
    "nombre": "Walter Wesely GmbH",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Niederösterreich",
    "provincia": "Niederösterreich",
    "localidad": "St. Pölten",
    "lat": null,
    "lon": null,
    "telefono": "+43 2742 3930",
    "web": "https://www.wesely.at/wohnmobil/uebersicht",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Praterstra%C3%9Fe%205%2C%203100%20St.%20P%C3%B6lten%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-028",
    "nombre": "WebCamping.at",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Tirol",
    "provincia": "Tirol",
    "localidad": "Wiesing",
    "lat": null,
    "lon": null,
    "telefono": "+43 660 6407701",
    "web": "https://webcamping.at/",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Bradl%20332%2C%206210%20Wiesing%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-029",
    "nombre": "AL-KO Kundencenter Österreich",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Tirol",
    "provincia": "Tirol",
    "localidad": "Ramsau im Zillertal",
    "lat": null,
    "lon": null,
    "telefono": "+43 5282 3360 449",
    "web": "https://www.alko-tech.com/de_at/Service/Kundencenter",
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Talstra%C3%9Fe%20150%2C%206284%20Ramsau%20im%20Zillertal%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-030",
    "nombre": "WM Camper",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Oberösterreich",
    "provincia": "Oberösterreich",
    "localidad": "Walding",
    "lat": null,
    "lon": null,
    "telefono": "+43 7234 87522",
    "web": null,
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Greism%C3%BChlweg%201%2C%204111%20Walding%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-031",
    "nombre": "Gritsch-Mobile",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Steiermark",
    "provincia": "Steiermark",
    "localidad": "Tillmitsch",
    "lat": null,
    "lon": null,
    "telefono": "+43 664 4176269",
    "web": null,
    "google_maps": "https://www.google.com/maps/search/?api=1&query=R%C3%B6merweg%201b%2C%208434%20Tillmitsch%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  },
  {
    "id": "taller-at-032",
    "nombre": "Caravan Technik Center",
    "tipo": "taller",
    "pais": "Austria",
    "comunidad_autonoma": "Niederösterreich",
    "provincia": "Niederösterreich",
    "localidad": "Stetten",
    "lat": null,
    "lon": null,
    "telefono": "+43 676 4480447",
    "web": null,
    "google_maps": "https://www.google.com/maps/search/?api=1&query=Sandstra%C3%9Fe%205A%2C%202100%20Stetten%2C%20%C3%96sterreich",
    "descripcion": "Taller o centro técnico especializado en autocaravanas, caravanas y vehículos de camping, verificado mediante directorios oficiales del sector."
  }
]
